name: mini_weather_app
description: A simple & mini feature weather application


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.21.1
  flutter_bloc: ^8.1.1
  country_state_city_picker: ^1.2.8
  firebase_auth: ^3.7.0
  fluttertoast: ^8.0.9
  cloud_firestore: ^3.4.6
  dio: ^4.0.6
  geolocator: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

